services:
  app:
    container_name: locadorapi
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://localhost:5432/locador
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - db

  db:
    container_name: postgres_db
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: locador
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}